- name: install required packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python-software-properties
    - software-properties-common
    - python-pip
